### ISSUE TITLE
Help with buttons

### ISSUE THREAD

**Issue by Riv67** [Riv67/saas-website#2]
@muxlowc @mackenzierose
I’m hoping to get some help for styling my buttons. They were styled and looked how I wanted, but when I linked them with the <a href> tag (e.g link to the sign up page for the “sign up” button) the text turned black and i can’t seem to override it in css. I want to make it white, any advice?

**Comment by muxlowc** [comment]
@Riv67  looks like all of your a tags are set to be black. so if you want just the a tags inside your buttons to be white you can do this in your main.css

.btn a {
  color: #fff;
}
+add a hover state as well.

Hope that answers your question!

**Comment by Riv67** [comment]
@muxlowc Oh I see, thanks!! That worked great!

I’d also love any advice on where to start regarding making the site responsive. All my grids are responsive, but I’ve been trying to make changes to the nav and type sizes with no luck so far. I’ve tried media queries, having two different nav sections for small and large sizes (then using display: none) and changing my css classes. Not sure what else to try to make it look good at a smaller size. Any suggestions?

**Comment by MacKenzieRose** [comment]
For this stage in your coding career, it's looking pretty responsive :)

Is there a specific visual change I can help you make?

**Comment by Riv67** [comment]
@mackenzierose Haha okay thanks! In that case maybe I don’t have to change as much as I thought!

I was mostly wondering if the navigation has to look different on mobile sizes? Right now the nav items can fit in one line and still look good, but should they be in a drop down or stacked in order to be responsive or can I leave it how it is?

**Comment by muxlowc** [comment]
@Riv67  you could center align it maybe? but otherwise, it looks great! Just what MacKenzie said-it's looking pretty responsive to me :)

**Comment by Riv67** [comment]
Okay sounds good, thanks so much for both of your help!!
